unique_dicom_tags = (" Content Time ",
" Referenced SOP Instance UID ",
" Code Value ",
" Temporal Position Identifier ",
" Coding Scheme Designator ",
" Series Instance UID ",
" Referenced SOP Class UID ",
" Window Center ",
" Instance Number ",
" Private Creator ",
" [Slice Number MR] ",
" Code Meaning ",
" Rescale Type ",
" Window Width ",
" Dimension Description Label ",
" In-Stack Position Number ",
" Operating Mode Type ",
" Referenced Frame Number ",
" [Unknown] ",
" SOP Instance UID ",
" Temporal Position Index ",
" Operating Mode ",
" Dimension Index Pointer ",
" [Diffusion Direction] ",
" Respiratory Signal Source ",
" [Chemical Shift] ",
" Pixel Presentation ",
" Specific Absorption Rate Definition ",
" Partial Fourier ",
" Instance Creator UID ",
" Complex Image Component ",
" Parallel Acquisition Technique ",
" [Stack Type] ",
" Volume Based Calculation Technique ",
" Specific Absorption Rate Value ",
" Blood Signal Nulling ",
" Intervals Rejected ",
" Acquisition Contrast ",
" Scanning Sequence ",
" Repetition Time ",
" Context Group Extension Flag ",
" Spacing Between Slices ",
" Echo Number(s) ",
" T2 Preparation ",
" Heart Rate ",
" Dimension Organization UID ",
" [Chemical Shift Number MR] ",
" Echo Train Length ",
" Low R-R Value ",
" Rescale Slope ",
" k-space Filtering ",
" SOP Class UID ",
" Instance Creation Date ",
" [Diffusion Direction AP] ",
" Parallel Reduction Factor out-of-plane ",
" [Stack Slice Number] ",
" Inversion Recovery ",
" Rescale Intercept ",
" Diffusion Anisotropy Type ",
" Parallel Acquisition ",
" Multiple Spin Echo ",
" Flow Compensation ",
" [Slice Orientation] ",
" Tag Thickness ",
" Receive Coil Name ",
" [Number of Stack Slices] ",
" Gradient Echo Train Length ",
" Context Group Extension Creator UID ",
" Spatial Pre-saturation ",
" Imaging Frequency ",
" Rectilinear Phase Encode Reordering ",
" Echo Time ",
" Intervals Acquired ",
" Tagging ",
" Number of Phase Encoding Steps ",
" Frame Reference DateTime ",
" [Image Type ED ES] ",
" [Diffusion B-Factor] ",
" [Stack Radial Angle] ",
" [Image Enhanced] ",
" [Phase Number] ",
" Inversion Time ",
" Magnetization Transfer ",
" Receive Coil Manufacturer Name ",
" Frame Acquisition DateTime ",
" Instance Creation Time ",
" Volumetric Properties ",
" Flip Angle ",
" Number of Averages ",
" Content Date ",
" Metabolite Map Description ",
" Transmitter Frequency ",
" MR Acquisition Frequency Encoding Steps ",
" Percent Phase Field of View ",
" Study Instance UID ",
" Sequence Variant ",
" Imaged Nucleus ",
" Parallel Reduction Factor In-plane ",
" Transmit Coil Name ",
" MR Acquisition Phase Encoding Steps out-of-plane ",
" Slice Thickness ",
" Partial Fourier Direction ",
" Frame Laterality ",
" Spoiling ",
" Multi-Coil Element Name ",
" Multi-Coil Element Used ",
" [Syncra Scan Type] ",
" Stack ID ",
" Pixel Bandwidth ",
" Transmit Coil Type ",
" Percent Sampling ",
" Receive Coil Type ",
" Gradient Output ",
" Coding Scheme Version ",
" [Diffusion Direction FH] ",
" High R-R Value ",
" RF Echo Train Length ",
" In-plane Phase Encoding Direction ",
" Gradient Output Type ",
" Frame Acquisition Duration ",
" [Stack Radial Axis] ",
" [Diffusion Direction RL] ",
" Quadrature Receive Coil ",
" Functional Group Pointer ",
" MR Acquisition Phase Encoding Steps in-plane ",
" Transmit Coil Manufacturer Name ",
" Parallel Reduction Factor Second In-plane ",
" Number of Temporal Positions ",
" Effective Echo Time ",
" Spectrally Selected Excitation ")
